### ISSUE TITLE
Feature request: Hotkey to bookmark current tree

### ISSUE THREAD

**Issue by a13ph** [Lej77/bookmark-tree-for-tree-style-tab#2]
First of all, my thanks and appreciation for such a useful extension! ❤️ 
Bridging Tree Style Tabs and bookmarks is a direction I really long for. 
This suggestion is in no way a demanding one, mostly for discussion and as a reminder for myself.

Currently, the only way to bookmark a tree via keyboard is to do F6, Shift-Tab till current tab element is focused, Menu key or Shift-F10, then use the accelerator key (which can be customized in extension settings). I might map this using AHK or similar tools, but native solution is preferred for robustness and crossplatform compatibility.

There is even a native hotkey configuration screen in Firefox [Nightly] now.

I assume this is a small change, I might even try to tackle it, if stars align.

**Comment by Lej77** [comment]
I released a new version of the extension (v2.8) that allows you to specify a keyboard shortcut to bookmark tree data. It has the same effect as right clicking the current tab and selecting the Bookmark Tree Data context menu item.
